const $=id=>document.getElementById(id);let data,previous;let latest=null;let comparisons=[];let plantGeneration=0;let plantTimer;
const recipe=(id,name,inputs,outputs,duration=60,extra={})=>({id,name,inputs,outputs,duration,power:0,workers:0,maintenance:0,count:0,load:1,min:0,max:null,cost:1,status:'待核验',source:'示例数据，请对照目标版本游戏确认',...extra});
const examples={
reactors:window.NuclearCatalog,
basic:{version:'合成演示 · 非游戏配方',recipes:[recipe('smelt','冶炼',{ore:2},{iron:1},30,{power:1,workers:4,count:2,buildingId:'demo_furnace',buildingName:'演示熔炉'}),recipe('smelt_alt','冶炼替代配方（合成）',{ore:3},{iron:2},60,{power:1.5,workers:4,buildingId:'demo_furnace'}),recipe('parts','零件制造',{iron:2},{parts:1},60,{count:2})],policies:{ore:{import:true,cost:10},parts:{target:2}}},
nuclear:{version:'核燃料讨论模型 · 未核验 · 不含完整发电与辅助耗材',recipes:[recipe('fresh','新鲜浓缩',{YC:6},{U4:1,DU:5}),recipe('nr','NR II 燃料循环',{U4:2},{spent:2},60,{min:8,max:8}),recipe('pu','乏燃料提钚',{spent:8},{RU1:6,Pu:1}),recipe('blanket','乏燃料制毯',{spent:1},{blanket:3}),recipe('reenrich','回收铀浓缩',{RU1:4},{U4:1,DU:3}),recipe('core','钚制核心',{Pu:1},{core:4}),recipe('breeder','3× FBR',{core:16,blanket:48},{spentCore:16,EB:48},60,{min:2,max:2}),recipe('zero','0× FBR',{core:8},{spentCore:8},60,{min:9,max:9}),recipe('recover','核心回收',{spentCore:16},{core:12}),recipe('split','浓缩毯分离',{EB:8},{blanket:6,core:2}),recipe('du','DU 制毯',{DU:10,EB:2},{blanket:4}),recipe('ycblanket','黄饼制毯',{YC:3},{blanket:1})],policies:{YC:{import:true,cost:1000},DU:{surplus:true},EB:{surplus:true}}},
farm:{version:'农业接口演示 · 合成轮作数据 · 不可作为游戏建造依据',recipes:[recipe('rotation','玉米/大豆完整轮作',{water:120,fertilizer:4},{corn:24,soy:12},240,{workers:20,maintenance:2,count:3,source:'用于演示完整轮作平均化；需替换周期、实际收成和肥料需求'})],policies:{water:{import:true},fertilizer:{import:true},corn:{target:12},soy:{surplus:true}}}
};
function elem(tag,text){let e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
function field(row,value,type,change){let td=elem('td'),i=elem('input');i.type=type;if(type==='checkbox')i.checked=!!value;else{i.value=value??'';i.step='any'}i.onchange=()=>{change(type==='checkbox'?i.checked:i.value===''?null:Number(i.value));sync()};td.append(i);row.append(td)}
function sync(){$('editor').value=JSON.stringify(data,null,2)}
function render(){prepareBuildings();renderBuildings();sync();$('buildingLimit').value=data.buildingLimit??'';$('version').textContent=data.version;$('machines').replaceChildren();$('policies').replaceChildren();for(const r of data.recipes.filter(r=>!r.reactorType)){let tr=elem('tr'),td=elem('td',r.name);td.append(elem('p',`${r.status||'未标记'} · ${r.source||'无来源'}`));tr.append(td);for(const [k,v]of [['min',0],['max',null]])field(tr,r[k]??v,'number',x=>r[k]=x);field(tr,r.full??false,'checkbox',x=>r.full=x);$('machines').append(tr)}data.policies??={};const ps=[...new Set(data.recipes.flatMap(r=>[...Object.keys(r.inputs),...Object.keys(r.outputs)]))].sort();for(const p of ps){const pol=data.policies[p]??={};let tr=elem('tr');tr.append(elem('td',productLabel(p)+productUnit(p)));for(const [k,type,v]of [['target','number',0],['import','checkbox',false],['cap','number',null],['cost','number',100],['surplus','checkbox',false]])field(tr,pol[k]??v,type,x=>pol[k]=x);$('policies').append(tr)}sync();$('results').replaceChildren();$('message').textContent='数据已应用；请重新计算。'}
function table(headers,rows){let t=elem('table'),head=elem('tr');headers.forEach(x=>head.append(elem('th',x)));t.append(head);rows.forEach(row=>{let tr=elem('tr');row.forEach(x=>tr.append(elem('td',x)));t.append(tr)});let wrap=elem('div');wrap.className='scroll';wrap.append(t);return wrap}
const fmt=v=>Math.abs(v)<1e-7?'0':Number(v.toFixed(5)).toString();
async function run(mode){$('message').textContent='计算中…';try{const response=await fetch('/api/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const r=await response.json();if(!r.ok)throw Error(r.message);$('results').replaceChildren();let cards=elem('div');cards.className='cards';for(const [k,title]of [['power','净耗电 MW'],['workers','配置工人'],['maintenance','维护等效估算'],['buildings','建筑总数']]){let c=elem('div',title);c.className='card';c.append(elem('strong',fmt(r.totals[k])));cards.append(c)}$('results').append(cards,elem('h2','配方运行量与独占建筑建议'),table(['配方','等效满载量','整数建筑','平均负荷'],r.recipes.filter(x=>x.rate>1e-7).map(x=>[x.name,fmt(x.rate),x.buildings,fmt(x.load*100)+'%'])),elem('h2','资源平衡（物料 /60，电力与机械功 MW）'),table(['物料','生产净值','外部输入','目标','剩余 / 缺口'],r.flows.map(x=>[productLabel(x.product)+productUnit(x.product),fmt(x.net),fmt(x.import),fmt(x.target),fmt(x.remainder)])));if(previous){$('results').append(elem('h2','与上一次成功计算比较'),table(['物料','剩余变化 /60'],r.flows.map(x=>[x.product,fmt(x.remainder-(previous.flows.find(y=>y.product===x.product)?.remainder??0))])))}latest={result:r,scenario:structuredClone(data)};previous=r;if(r.warnings.length){$('results').append(elem('h2','数据校验提醒'),elem('p',r.warnings.join('；')))}$('message').textContent=mode==='integer'?'整数优化成功。若需要指定净发电，请设置电力目标；当前目标最小化加权成本。强制满载配方运行量等于整数建筑数，其余配方允许部分负荷。目标：建筑数×配方成本 + 进口量×进口成本。':mode==='solve'?'连续配平成功。建筑向上取整后按显示负荷运行；不代表整数建筑全部满载。优化目标：配方运行量×成本 + 外部输入×成本。':'核算完成。负值表示缺口，正值表示剩余；本模式不自动补资源。'}catch(e){$('message').textContent=e.message;$('results').replaceChildren()}}
$('load').onclick=()=>{data=structuredClone(examples[$('example').value]);previous=null;render()};$('apply').onclick=()=>{try{const d=JSON.parse($('editor').value);if(!Array.isArray(d.recipes)||!d.recipes.length)throw Error('缺少 recipes');for(const r of d.recipes)if(!r.inputs||!r.outputs||!r.id)throw Error('配方需要 id、inputs、outputs');data=d;render()}catch(e){$('message').textContent=e.message}};
$('audit').onclick=()=>run('audit');$('solve').onclick=()=>run('solve');$('integer').onclick=()=>run('integer');$('buildingLimit').onchange=()=>{data.buildingLimit=$('buildingLimit').value===''?null:Number($('buildingLimit').value);sync()};
let desktopScenarios=null;let desktopStorageError=false;
window.addEventListener('pywebviewready',async()=>{try{desktopScenarios=await window.pywebview.api.read_scenarios();refresh();if(typeof window.pywebview.api.read_draft==='function'){const draft=await window.pywebview.api.read_draft();if(draft){data=draft.scene;render();$('editor').value=draft.editor??$('editor').value;if(draft.example)$('example').value=draft.example}$('message').textContent='开发模式：网页保存后自动刷新，Python 保存后自动重启；测试场景自动恢复。'}else $('message').textContent='桌面版已就绪；方案保存到本地文件。'}catch(e){desktopStorageError=true;$('message').textContent='本地方案读取失败：'+e.message+'；请检查用户目录 scenarios.json，修复后重新启动。'}});
function saved(){return desktopScenarios??JSON.parse(localStorage.getItem('coi-scenarios')||'{}')}function refresh(){let s=saved();$('saved').replaceChildren();Object.keys(s).forEach(k=>{let o=elem('option',k);o.value=k;$('saved').append(o)})}
$('save').onclick=async()=>{if(desktopStorageError||window.pywebview&&desktopScenarios===null){$('message').textContent='本地方案尚未成功读取，请稍后或修复文件后重启。';return}const name=prompt('方案名称');if(!name)return;let s=structuredClone(saved());s[name]=structuredClone(data);try{if(desktopScenarios!==null){await window.pywebview.api.write_scenarios(s);desktopScenarios=s}else localStorage.setItem('coi-scenarios',JSON.stringify(s));refresh();$('message').textContent=desktopScenarios!==null?'已保存到本地方案文件；升级程序后保留。':'已保存到当前浏览器；跨设备请导出 JSON。'}catch(e){$('message').textContent='保存失败：'+e.message}};$('restore').onclick=()=>{let d=saved()[$('saved').value];if(d){data=d;render()}};
$('export').onclick=()=>{let url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=elem('a');a.href=url;a.download='coi-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{$('editor').value=await $('file').files[0].text();$('apply').click()}catch(e){$('message').textContent=e.message}};let viewPreferences={};try{viewPreferences=JSON.parse(localStorage.getItem('coi-building-view')||'{}')}catch{}
$('buildingView').value=['extra','large','medium','small','list','details','tiles','content'].includes(viewPreferences.view)?viewPreferences.view:'content';$('mergeBuildings').checked=viewPreferences.merge!==false;
function saveBuildingView(){localStorage.setItem('coi-building-view',JSON.stringify({view:$('buildingView').value,merge:$('mergeBuildings').checked}))}
$('buildingView').onchange=$('mergeBuildings').onchange=()=>{saveBuildingView();renderBuildings()};
data=structuredClone(examples[new URLSearchParams(location.search).get('example')]||examples.basic);$('example').value=new URLSearchParams(location.search).get('example') in examples?new URLSearchParams(location.search).get('example'):'basic';render();refresh();

function compareRender(){ $('comparison').replaceChildren();if(!comparisons.length)return;$('comparison').append(table(['方案','模式','建筑','配置工人','净耗电 MW','进口物料种类'],comparisons.map(x=>[x.name,x.result.mode,fmt(x.result.totals.buildings),fmt(x.result.totals.workers),fmt(x.result.totals.power),x.result.flows.filter(f=>f.import>1e-7).length])));const products=[...new Set(comparisons.flatMap(x=>x.result.flows.map(f=>f.product)))];$('comparison').append(table(['物料',...comparisons.map(x=>x.name+' 进口 /60')],products.map(p=>[p,...comparisons.map(x=>fmt(x.result.flows.find(f=>f.product===p)?.import??0))])))}
$('pinResult').onclick=()=>{if(!latest){$('message').textContent='先完成一次计算。';return}comparisons.push({name:$('compareName').value.trim()||'方案 '+(comparisons.length+1),...structuredClone(latest)});compareRender()};$('clearCompare').onclick=()=>{comparisons=[];compareRender()};$('exportResult').onclick=()=>{if(!latest)return;const url=URL.createObjectURL(new Blob([JSON.stringify(latest,null,2)],{type:'application/json'}));const a=elem('a');a.href=url;a.download='coi-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};

function prepareBuildings(){
 data.buildings??=[];
 const known=new Map(data.buildings.map(b=>[b.id,b]));
 for(const r of data.recipes){r.buildingId??='machine_'+r.id;if(!known.has(r.buildingId)){let kind=r.id==='rotation'?'farm':['nr','breeder','zero'].includes(r.id)?'reactor':['smelt'].includes(r.id)?'furnace':'factory';const b={id:r.buildingId,name:r.buildingName||r.name+'设备',icon:'/icons/'+kind+'.svg',iconSource:'项目自绘 SVG',status:'示例建筑映射，待核验'};data.buildings.push(b);known.set(b.id,b)}}
 const mapping={smelt:'Blast Furnace.png',smelt_alt:'Blast Furnace.png',parts:'Assembly (Electric).png',fresh:'Enrichment Plant.png',reenrich:'Enrichment Plant.png',split:'Enrichment Plant.png',nr:'Nuclear Reactor II.png',breeder:'Fast Breeder Reactor.png',zero:'Fast Breeder Reactor.png',pu:'Nuclear Reprocessing Plant.png',blanket:'Nuclear Reprocessing Plant.png',recover:'Nuclear Reprocessing Plant.png',core:'Chemical Plant.png',du:'Chemical Plant.png',ycblanket:'Chemical Plant.png',rotation:'Greenhouse II.png'};
 for(const r of data.recipes){const b=known.get(r.buildingId),asset=(window.WikiIcons||{})[r.wikiIcon||b?.wikiIcon||mapping[r.id]];if(asset&&b&&(!b.icon||b.iconSource==='项目自绘 SVG'||b.iconSource==='Captain of Industry Wiki'))Object.assign(b,{icon:asset.path,iconSource:'Captain of Industry Wiki',iconSourcePage:asset.sourcePage,iconLicense:asset.licenseText,iconNoticePath:asset.noticePath,iconSummary:asset.summary})}
 if(!data.instances){data.instances=[];for(const r of data.recipes){const count=r.count||0;for(let i=0;i<Math.ceil(count);i++)data.instances.push({id:crypto.randomUUID(),buildingId:r.buildingId,recipeId:r.id,load:Math.min(1,Math.max(0,count-i))*(r.load??1),enabled:true})}}
}
function buildingIcon(b){const img=elem('img');img.alt=b.name+'图标';const fallback='/icons/factory.svg';const path=b.icon||fallback;img.src=/^\/icons\/[a-zA-Z0-9_.-]+$/.test(path)?path:fallback;img.onerror=()=>{img.onerror=null;img.src=fallback};img.title=b.iconSource||'来源未标记';return img}
function updateBuilding(){sync();renderBuildings()}
function renderBuildings(){
 const selectedType=$('buildingType').value;
 $('buildingType').replaceChildren();for(const b of data.buildings.filter(b=>data.recipes.some(r=>r.buildingId===b.id))){const o=elem('option',b.name);o.value=b.id;$('buildingType').append(o)}
 if([...$('buildingType').options].some(o=>o.value===selectedType))$('buildingType').value=selectedType;
 $('buildingCards').className='building-grid view-'+$('buildingView').value;$('buildingCards').replaceChildren();const totals={};let totalPower=0,totalWorkers=0;
 for(const members of BuildingViews.groups(data.instances,data.recipes,$('mergeBuildings').checked)){
  const first=members[0],idx=data.instances.indexOf(first);const i=new Proxy(first,{set(target,key,value){for(const member of members)member[key]=value;return true}});
  const b=data.buildings.find(b=>b.id===i.buildingId);const r=data.recipes.find(r=>r.id===i.recipeId);let card=elem('article');card.className='building-card';if(!b||!r){card.append(elem('p','建筑或配方已删除，请移除失效建筑'));let remove=elem('button','移除');remove.onclick=()=>{data.instances=data.instances.filter(x=>x.id!==i.id);updateBuilding()};card.append(remove);$('buildingCards').append(card);continue}
  card.append(buildingIcon(b),elem('h3',b.name+(members.length>1?' ×'+members.length:' #'+(idx+1))));
  const preview=elem('p',(i.enabled===false?'停机':'运行')+' · '+r.name+' · '+(r.reactorType?'档位 '+(i.level??(r.reactorType==='nr1'?3:4)):'负荷 '+fmt(i.load*100)+'%')+((r.reactorType||r.plantRole)?' · '+(i.station||'主电站'):''));if(r.reactorType){preview.textContent+=' · '+(i.control==='auto'?'自动 / 平均 '+(i.averageLevel??i.level):'手动');if(r.reactorType==='nr2')preview.textContent+=' · '+(i.fuel==='mox_rod'?'MOX 燃料棒':'铀燃料棒');if(r.reactorType==='fbr')preview.textContent+=' · '+(i.breeding??1)+'×增殖'+((i.breeding??1)!==0?' / 毯供料 '+fmt((i.blanketFraction??1)*100)+'%':'')}preview.className='building-summary';card.append(preview);
  const body=elem('details');body.className='building-body';body.open=$('buildingView').value==='content';body.append(elem('summary',members.length>1?'编辑本组 '+members.length+' 座':'编辑建筑'));card.append(body);const shell=card;card=body;const select=elem('select');select.setAttribute('aria-label',b.name+' #'+(idx+1)+' 配方');for(const rr of data.recipes.filter(r=>r.buildingId===b.id)){let o=elem('option',rr.name);o.value=rr.id;select.append(o)}select.value=i.recipeId;select.onchange=()=>{i.recipeId=select.value;updateBuilding()};if(!r.reactorType)card.append(select);if(r.plantRole)card.append(elem('p','下方是设定容量；实际稳态分配见核电站容量检查。'));if(r.reactorType)card.append(reactorControls(i,r));if(r.reactorType||r.plantRole)card.append(stationControls(i));if(b.iconSourcePage){const credit=elem('details'),summary=elem('summary','图标来源与许可');credit.append(summary,elem('p',b.iconSummary||''),elem('p',b.iconLicense||''));const link=elem('a','查看 Wiki 原文件页');if(/^https:\/\/wiki\.coigame\.com\//.test(b.iconSourcePage)){link.href=b.iconSourcePage;link.target='_blank';link.rel='noopener noreferrer';credit.append(link)}card.append(credit)}
  const bar=elem('div');bar.className='bar';const label=elem('label','负荷 % '),load=elem('input');load.type='number';load.min=0;load.max=100;load.step='any';load.value=i.load*100;load.onchange=()=>{const v=Number(load.value);if(!Number.isFinite(v)||v<0||v>100){load.value=i.load*100;return}i.load=v/100;updateBuilding()};label.append(load);if(!r.reactorType)bar.append(label);
  let enabledLabel=elem('label','运行 '),enabled=elem('input');enabled.type='checkbox';enabled.checked=i.enabled!==false;enabled.onchange=()=>{i.enabled=enabled.checked;updateBuilding()};enabledLabel.append(enabled);bar.append(enabledLabel);card.append(bar);
  try{const f=BuildingMath.flows(i,data.recipes,data.reactorParameters);for(const side of ['inputs','outputs'])for(const p of Object.keys(f[side]))f[side][p]*=members.length;f.power*=members.length;f.workers*=members.length;totalPower+=f.power;totalWorkers+=f.workers;for(const side of ['inputs','outputs']){let line=elem('div',(side==='inputs'?'消耗：':'产出：')+Object.entries(f[side]).map(([p,q])=>productLabel(p)+' '+fmt(q)+productUnit(p)).join(' · '));line.className='io '+(side==='inputs'?'in':'out');card.append(line);for(const [p,q]of Object.entries(f[side])){totals[p]??={input:0,output:0};totals[p][side==='inputs'?'input':'output']+=q}}const compact=elem('div');compact.className='building-columns';for(const [title,value]of [['总消耗',Object.entries(f.inputs).map(([p,q])=>productLabel(p)+' '+fmt(q)+productUnit(p)).join(' · ')||'—'],['总产出',Object.entries(f.outputs).map(([p,q])=>productLabel(p)+' '+fmt(q)+productUnit(p)).join(' · ')||'—'],['净耗电 / 工人',fmt(f.power)+' MW / '+f.workers]]){const cell=elem('div');cell.append(elem('small',title),elem('div',value));compact.append(cell)}shell.insertBefore(compact,body);card.append(elem('p','净耗电 '+fmt(f.power)+' MW · 配置工人 '+f.workers+' · '+(r.status||'未校验')))}catch(e){card.append(elem('p',e.message))}
  let actions=elem('div');actions.className='bar';let copy=elem('button','复制一座'),remove=elem('button',members.length>1?'移除本组':'移除');copy.onclick=()=>{data.instances.push({...i,id:crypto.randomUUID()});updateBuilding()};remove.onclick=()=>{data.instances=data.instances.filter(x=>!members.includes(x));updateBuilding()};actions.append(copy,remove);if(members.length>1){const split=elem('button','逐座编辑');split.onclick=()=>{$('mergeBuildings').checked=false;saveBuildingView();renderBuildings()};actions.append(split)}card.append(actions);$('buildingCards').append(shell);
 }
 $('liveFlows').replaceChildren(elem('p','共 '+data.instances.length+' 座 · 设定净耗电（非实际发电） '+fmt(totalPower)+' MW · 配置工人 '+totalWorkers),table(['物料','总消耗','总产出','净值'],Object.entries(totals).sort().map(([p,f])=>[productLabel(p)+productUnit(p),fmt(f.input),fmt(f.output),fmt(f.output-f.input)])));
 schedulePlantCheck();
}
$('addBuilding').onclick=()=>{const buildingId=$('buildingType').value;const r=data.recipes.find(r=>r.buildingId===buildingId);if(!r)return;data.instances.push(defaultInstance(r));updateBuilding()};

function productLabel(p){const [base,group]=p.split('@');return (data.productNames?.[base]||base)+(group?' · '+group:'')}
function productUnit(p){return ['mechanical_mw','electricity'].includes(p.split('@')[0])?' MW':'/60'}
function defaultInstance(r){return {id:crypto.randomUUID(),buildingId:r.buildingId,recipeId:r.id,load:1,enabled:true,...(r.reactorType?{level:r.reactorType==='nr1'?3:4,fuel:'uranium_rod',breeding:1,blanketFraction:1,control:'manual',averageLevel:r.reactorType==='nr1'?3:4}:{}),...(r.reactorType||r.plantRole?{station:'主电站'}:{})}}
function choice(labelText,value,options,change){const label=elem('label',labelText+' '),input=elem('select');input.setAttribute('aria-label',labelText);for(const [v,text]of options){const o=elem('option',text);o.value=v;input.append(o)}input.value=value;input.onchange=()=>{change(input.value);updateBuilding()};label.append(input);return label}
function numericControl(labelText,value,min,max,change){const label=elem('label',labelText+' '),input=elem('input');input.type='number';input.step='any';input.min=min;if(max!==undefined)input.max=max;input.value=value??'';input.setAttribute('aria-label',labelText);input.onchange=()=>{const v=Number(input.value);if(!Number.isFinite(v)||v<min||max!==undefined&&v>max){input.value=value??'';return}change(input.value===''?null:v);updateBuilding()};label.append(input);return label}
function reactorControls(i,r){
 const box=elem('div'),max=r.reactorType==='nr1'?3:4;i.level??=max;i.control??='manual';
 box.append(choice(i.control==='auto'?'最高档位':'运行档位',i.level,Array.from({length:max},(_,j)=>[j+1,(j+1)+'档']),v=>{i.level=Number(v);i.averageLevel=Math.min(i.averageLevel??i.level,i.level)}));
 if(r.reactorType==='nr2')box.append(choice('燃料',i.fuel??'uranium_rod',[['uranium_rod','铀燃料棒'],['mox_rod','MOX 燃料棒']],v=>i.fuel=v));
 if(r.reactorType!=='nr1')box.append(choice('调节方式',i.control,[['manual','手动固定档位'],['auto','自动调节（平均估算）']],v=>{i.control=v;i.averageLevel??=i.level}));
 if(i.control==='auto')box.append(numericControl('预计平均档位',i.averageLevel??i.level,1,i.level,v=>i.averageLevel=v),elem('p','最低第一档；不推断自动调节行为，不含启停时间。'));
 if(r.reactorType==='fbr'){box.append(choice('增殖模式',i.breeding??1,[[0,'0× · 不增殖'],[1,'1× · 常规增殖'],[3,'3× · 蒸汽减至四分之一']],v=>i.breeding=Number(v)));if((i.breeding??1)!==0)box.append(numericControl('毯式实际供料 %',(i.blanketFraction??1)*100,0,100,v=>i.blanketFraction=v/100));box.append(elem('p','毯式增殖独立；供料不足不等于核心燃烧停机。'))}
 let button=elem('button','补齐本组发电配套');button.onclick=()=>addPlantEquipment(i.station||'主电站');box.append(button);return box;
}
function stationControls(i){const box=elem('div'),label=elem('label','电站组 '),input=elem('input');input.value=i.station||'主电站';input.setAttribute('aria-label','电站组');input.style.width='160px';input.onchange=()=>{i.station=input.value.trim()||'主电站';updateBuilding()};label.append(input);box.append(label);return box}
function addPlantEquipment(group){
 let superSteam=0,highSteam=0;
 for(const i of data.instances){const r=data.recipes.find(r=>r.id===i.recipeId);if(!r?.reactorType||(i.station||'主电站')!==group)continue;const f=BuildingMath.flows(i,data.recipes,data.reactorParameters);superSteam+=f.outputs.steam_super||0;highSteam+=f.outputs.steam_high||0}
 const steam=superSteam+highSteam,mechanical=superSteam/48*18+steam/48*18;
 const targets={super_turbine:superSteam/48,high_turbine:steam/48,low_turbine:steam/48,generator:mechanical/18,cooling:steam/96};
 for(const [buildingId,needed]of Object.entries(targets)){let have=data.instances.filter(i=>i.buildingId===buildingId&&(i.station||'主电站')===group).reduce((a,i)=>a+(i.enabled===false?0:i.load),0);const r=data.recipes.find(r=>r.buildingId===buildingId&&(buildingId!=='cooling'||r.inputs.steam_depleted));if(!r)continue;for(let n=0;n<Math.ceil(Math.max(0,needed-have)-1e-7);n++)data.instances.push({...defaultInstance(r),station:group})}
 updateBuilding();$('message').textContent='已补齐本组理想稳态发电配套；燃料生产设备由配平器另行求解。';
}
function schedulePlantCheck(){
 clearTimeout(plantTimer);const generation=++plantGeneration;
 if(!data.recipes.some(r=>r.reactorType)){$('plantReport').textContent='当前方案没有专用反应堆。加载“核电站专用模型”启用。';return}
 $('plantReport').textContent='计算本组蒸汽、机械功和发电容量…';
 plantTimer=setTimeout(async()=>{try{const response=await fetch('/api/plant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),report=await response.json();if(generation!==plantGeneration)return;if(!report.ok)throw Error(report.message);$('plantReport').replaceChildren(elem('p',report.assumption),elem('p','全厂容量毛发电 '+fmt(report.grossMW)+' MW · 已配置辅助链耗电 '+fmt(report.auxiliaryMW)+' MW · 容量净发电 '+fmt(report.netMW)+' MW'));for(const s of report.stations){const section=elem('section');section.append(elem('h3',s.station),table(['容量发电 MW','发电机上限 MW','主换热水 /60','回收水 /60','最低补水 /60'],[[fmt(s.grossMW),fmt(s.generatorCapacityMW),fmt(s.waterDemand),fmt(s.recoveredWater),fmt(s.makeupWater)]]));data.stationWater??={};section.append(numericControl('外部供水能力 /60（空=未确认）',data.stationWater[s.station],0,undefined,v=>{if(v===null)delete data.stationWater[s.station];else data.stationWater[s.station]=v}));for(const warning of s.warnings)section.append(elem('p',warning));section.append(table(['未处理蒸汽','数量 /60'],Object.entries(s.residual).filter(([p])=>p!=='mechanical_mw').map(([p,q])=>[productLabel(p),fmt(q)])));$('plantReport').append(section)}}catch(e){if(generation===plantGeneration)$('plantReport').textContent=e.message}},150);
}
$('applyPlan').onclick=()=>{
 if(!latest||latest.result.mode==='audit'){$('message').textContent='请先完成连续或整数配平。';return}
 const snapshot=structuredClone(latest.scenario),newInstances=snapshot.instances?.filter(i=>snapshot.recipes.find(r=>r.id===i.recipeId)?.reactorType)||[];
 for(const result of latest.result.recipes){if(result.rate<1e-7||result.id.startsWith('reactor:'))continue;const r=snapshot.recipes.find(r=>r.id===result.templateId);if(!r)continue;const count=Math.ceil(result.rate-1e-7);for(let j=0;j<count;j++)newInstances.push({...defaultInstance(r),load:result.rate/count,...(result.station?{station:result.station}:{})})}
 snapshot.instances=newInstances;data=snapshot;render();$('message').textContent='已根据计算时的场景生成建筑，核反应堆设置保留；可核算检查。';
};
